# Generated by Django 3.2.7 on 2022-04-04 17:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='id',
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
