# Generated by Django 3.2.7 on 2022-04-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_score_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'History'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-score'], 'verbose_name_plural': 'Score'},
        ),
    ]
