# Generated by Django 3.2.7 on 2022-03-22 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='user',
            field=models.ManyToManyField(related_name='Chore', to=settings.AUTH_USER_MODEL),
        ),
    ]
