# Generated by Django 3.2.7 on 2022-04-04 18:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20220404_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
