# Generated by Django 3.2.7 on 2022-04-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220323_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
