# Generated by Django 3.2.7 on 2022-04-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220404_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='points',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
