# Generated by Django 3.2.7 on 2022-04-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_score_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name_plural': 'Score'},
        ),
    ]
